config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wechatinfos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :welcome
  root 'welcome#index'


end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/wechatinfo.rb
class Wechatinfo
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wechatinfos_controller.rb
class WechatinfosController < ApplicationController
  before_action :set_wechatinfo, only: [:show, :edit, :update, :destroy]

  # GET /wechatinfos
  # GET /wechatinfos.json
  def index
    @wechatinfos = Wechatinfo.all
  end

  # GET /wechatinfos/1
  # GET /wechatinfos/1.json
  def show
  end

  # GET /wechatinfos/new
  def new
    @wechatinfo = Wechatinfo.new
  end

  # GET /wechatinfos/1/edit
  def edit
  end

  # POST /wechatinfos
  # POST /wechatinfos.json
  def create
    @wechatinfo = Wechatinfo.new(wechatinfo_params)

    respond_to do |format|
      if @wechatinfo.save
        format.html { redirect_to @wechatinfo, notice: 'Wechatinfo was successfully created.' }
        format.json { render :show, status: :created, location: @wechatinfo }
      else
        format.html { render :new }
        format.json { render json: @wechatinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wechatinfos/1
  # PATCH/PUT /wechatinfos/1.json
  def update
    respond_to do |format|
      if @wechatinfo.update(wechatinfo_params)
        format.html { redirect_to @wechatinfo, notice: 'Wechatinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @wechatinfo }
      else
        format.html { render :edit }
        format.json { render json: @wechatinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wechatinfos/1
  # DELETE /wechatinfos/1.json
  def destroy
    @wechatinfo.destroy
    respond_to do |format|
      format.html { redirect_to wechatinfos_url, notice: 'Wechatinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wechatinfo
      @wechatinfo = Wechatinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wechatinfo_params
      params.fetch(:wechatinfo, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wechatinfos_helper.rb
module WechatinfosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weiju</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wechatinfos/_form.html.erb
<%= form_with(model: wechatinfo, local: true) do |form| %>
  <% if wechatinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wechatinfo.errors.count, "error") %> prohibited this wechatinfo from being saved:</h2>

      <ul>
      <% wechatinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wechatinfos/edit.html.erb
<h1>Editing Wechatinfo</h1>

<%= render 'form', wechatinfo: @wechatinfo %>

<%= link_to 'Show', @wechatinfo %> |
<%= link_to 'Back', wechatinfos_path %>

app/views/wechatinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wechatinfos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wechatinfos.each do |wechatinfo| %>
      <tr>
        <td><%= link_to 'Show', wechatinfo %></td>
        <td><%= link_to 'Edit', edit_wechatinfo_path(wechatinfo) %></td>
        <td><%= link_to 'Destroy', wechatinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wechatinfo', new_wechatinfo_path %>

app/views/wechatinfos/new.html.erb
<h1>New Wechatinfo</h1>

<%= render 'form', wechatinfo: @wechatinfo %>

<%= link_to 'Back', wechatinfos_path %>

app/views/wechatinfos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wechatinfo_path(@wechatinfo) %> |
<%= link_to 'Back', wechatinfos_path %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-4">
    hello world!


  </div>
  <div class="col-md-4">
    hello world!


  </div>
  <div class="col-md-4">
    hello world!


  </div>
</div>